<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<Version>2.2</Version>
		<Nullable>disable</Nullable>
		<Authors>Chris Domino</Authors>
		<Company>Lines Of Code</Company>
		<Title>Blazor Web Workers</Title>
		<RepositoryType>git</RepositoryType>
		<NeutralLanguage>en-US</NeutralLanguage>
		<ImplicitUsings>disable</ImplicitUsings>
		<TargetFramework>net10.0</TargetFramework>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
		<RepositoryUrl>https://github.com/cdomino/LinesOfCode-WebWorkers</RepositoryUrl>
		<PackageProjectUrl>https://blazor-web-workers.azurewebsites.net</PackageProjectUrl>
		<PackageTags>Blazor; WASM; Web Worker; WebWorker; Web Workers; WebWorkers</PackageTags>
		<PackageReleaseNotes>See the "Changelog" section at the bottom of the readme.</PackageReleaseNotes>
		<Description>Remember when Blazor WASM was single threaded? Well you won't after installing this package! Use Blazor Web Workers to allow your UI to remain responsive while long running operations, well, blaze on background JavaScript threads.</Description>
	</PropertyGroup>
	<ItemGroup>
		<SupportedPlatform Include="browser" />
	</ItemGroup>
	<ItemGroup>
		<None Update="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Blazored.SessionStorage" Version="2.4.0" />
		<PackageReference Include="Microsoft.Extensions.Http" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="10.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.0" />
	</ItemGroup>
</Project>
